### ISSUE TITLE
[tomcat] 在conf/[Engine]/[Host] 下自定义context的问题

### ISSUE THREAD

**Issue by Gukie** [Gukie/spring-learning#1]
context可以定义在：
- web 应用程序的war包中的META-INFO/context.xml，并且conf/server.xml的Host配置了"copyXML=true"
- conf/server.xml的host下面定义多个context
- 在conf/[Engine]/[Host]下定义 (配置文件的名字，不一定需要跟web 应用程序的名字保持一致)

---
在conf/[Engine]/[Host]下定义的context, 为什么path一定要是一个相对于appBase的一个路径？而不能是一个自定义的呢？

比如，server.xml中的host如下
```
<Engine name="Catalina-shu" defaultHost="localhost">

      <!--For clustering, please take a look at documentation at:
          /docs/cluster-howto.html  (simple how to)
          /docs/config/cluster.html (reference documentation) -->
      <!--
      <Cluster className="org.apache.catalina.ha.tcp.SimpleTcpCluster"/>
      -->

      <!-- Use the LockOutRealm to prevent attempts to guess user passwords
           via a brute-force attack -->
      <Realm className="org.apache.catalina.realm.LockOutRealm">
        <!-- This Realm uses the UserDatabase configured in the global JNDI
             resources under the key "UserDatabase".  Any edits
             that are performed against this UserDatabase are immediately
             available for use by the Realm.  -->
        <Realm className="org.apache.catalina.realm.UserDatabaseRealm"
               resourceName="UserDatabase"/>
      </Realm>

      <Host name="localhost"  appBase="my-webapps"
            unpackWARs="false" autoDeploy="false">

        <!-- SingleSignOn valve, share authentication between web applications
             Documentation at: /docs/config/valve.html -->
        <!--
        <Valve className="org.apache.catalina.authenticator.SingleSignOn" />
        -->
		
		<Context path="" docBase="D:\\software\\apache-tomcat-9.0.10\\webapps\\ROOT"></Context> <!--必须要有一个default的context，否则 http://localhost:8443 不会拿到任何数据 -->
		
		<!--
		<Context path="/sample" docBase="non-mine/sample"></Context>
		<Context path="/example" docBase="D:\\software\\apache-tomcat-9.0.10\\webapps\\examples"></Context>
		-->
		
        <!-- Access log processes all example.
             Documentation at: /docs/config/valve.html
             Note: The pattern used is equivalent to using pattern="common" -->
        <Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs"
               prefix="localhost_access_log" suffix=".txt"
               pattern="%h %l %u %t &quot;%r&quot; %s %b" />

      </Host>
```

然后再 conf/Catalina-shu/localhost/下定义了一个 "11.xml" 的配置文件:
```
<?xml version="1.0" encoding="UTF-8"?>
<Context path="/sample" docBase="/non-mine/sample/"></Context>
```

在 $CATALINA_BASE/my-webapps下，拥有一个web应用程序$CATALINA_BASE/my-webapps/non-mine/sample

可是在启动的时候，报以下错误：
```
30-Jul-2018 09:39:11.161 严重 [main] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start: 
 org.apache.catalina.LifecycleException: Failed to start component [org.apache.catalina.webresources.StandardRoot@f2ff811]
	at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:441)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
	at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4758)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4893)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:742)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:718)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:703)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:630)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1840)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:525)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:424)
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1585)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:308)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:424)
	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:367)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:966)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:839)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1427)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1417)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:943)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:258)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:770)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:682)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:350)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492)
Caused by: java.lang.IllegalArgumentException: The main resource set specified [D:\software\apache-tomcat-9.0.10\my-webapps\11] is not valid
	at org.apache.catalina.webresources.StandardRoot.createMainResourceSet(StandardRoot.java:749)
	at org.apache.catalina.webresources.StandardRoot.startInternal(StandardRoot.java:706)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	... 41 more

30-Jul-2018 09:39:11.177 严重 [main] org.apache.catalina.startup.HostConfig.deployDescriptor Error deploying deployment descriptor [D:\software\apache-tomcat-9.0.10\conf\Catalina-shu\localhost\11.xml]
 java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [org.apache.catalina.webresources.StandardRoot@f2ff811]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:746)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:718)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:703)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:630)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1840)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:525)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:424)
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1585)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:308)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:424)
	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:367)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:966)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:839)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1427)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1417)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:943)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:258)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:770)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:682)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:350)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492)
```

**Comment by Gukie** [comment]
发现，如果将 conf/Catalina-shu/localhost/11.xml 修改为：
```
<Context path="/non-mine/sample" docBase=""></Context>
```
就可以启动;
但是方位的时候，地址是： http://localhost:8080/non-mine/sample, 而不是 http://localhost:8080/sample

**Comment by Gukie** [comment]
在 conf/server.xml 下定义的context，就可以 通过  http://localhost:8080/sample 访问
```
 <Host name="localhost"  appBase="my-webapps"
            unpackWARs="false" autoDeploy="false">

        <!-- SingleSignOn valve, share authentication between web applications
             Documentation at: /docs/config/valve.html -->
        <!--
        <Valve className="org.apache.catalina.authenticator.SingleSignOn" />
        -->
		
		<Context path="" docBase="D:\\software\\apache-tomcat-9.0.10\\webapps\\ROOT"></Context> <!--必须要有一个default的context，否则 http://localhost:8443 不会拿到任何数据 -->
			
		<Context path="/sample" docBase="non-mine/sample"></Context>
		<!--
		<Context path="/example" docBase="D:\\software\\apache-tomcat-9.0.10\\webapps\\examples"></Context>
		-->
		
        <!-- Access log processes all example.
             Documentation at: /docs/config/valve.html
             Note: The pattern used is equivalent to using pattern="common" -->
        <Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs"
               prefix="localhost_access_log" suffix=".txt"
               pattern="%h %l %u %t &quot;%r&quot; %s %b" />

      </Host>
```

**Comment by Gukie** [comment]
莫非，在 conf/[Engine]/[host]下的 配置文件的相对路径，不是 conf/server.xml中的host中的appBase?

**Comment by Gukie** [comment]
> 莫非，在 conf/[Engine]/[host]下的 配置文件的相对路径，不是 conf/server.xml中的host中的appBase?

应该没关系，因为将path设置为一个绝对路径，也是不行..此时从日志的内容看，他们是被ignore掉了的
```
30-Jul-2018 09:52:06.685 警告 [main] org.apache.catalina.startup.HostConfig.deployDescriptor The path attribute with value [/sample] in deployment descriptor [D:\software\apache-tomcat-9.0.10\conf\Catalina-shu\localhost\11.xml] has been ignored
30-Jul-2018 09:52:06.686 警告 [main] org.apache.catalina.startup.HostConfig.deployDescriptor A docBase [D:\software\apache-tomcat-9.0.10\my-webapps\non-mine] inside the host appBase has been specified, and will be ignored
```

**Comment by Gukie** [comment]
同样的context配置，放在 conf/server.xml 和 conf/[Engine]/[Host]/11.xml ，前者可以生效，后者不能生效
```
<Context path="/sample1" docBase="D:/tmp/webapps/sample"></Context>
```

**Comment by Gukie** [comment]
在 conf/[Engine]/[Host]/11.xml 中，配置如下信息
```
<Context  docBase="D:/tmp/webapps/sample"></Context>
```
启动之后，输入 http://localhost:8080/11/， 发现是可以访问到到。 在 $CATALINA_BASE/work下是可以看到有 11 这个 目录的。

这个可能是由于 conf/[Engine]/[Host]/11.xml 的配置，默认是 “11” 这个path

**Comment by Gukie** [comment]
从文档中可以知道：
### docBase
只有在一下两种情况下才需要配置 docBase，默认的docBase就是 appBase
- 在 server.xml中配置的context
- 或者是 docBase不在 appBase下

context的path
- 只有在 conf/server.xml中才需要配置，其他地方不需要配置
- 其他地方的context path，tomcat会从 conf/[Engine]/[Host]下的context配置文件名或者 docBase的文件名中 猜出来
> This attribute must only be used when statically defining a Context in server.xml. In all other circumstances, the path will be inferred from the filenames used for either the .xml context file or the docBase.

所以，在 conf/[Engine]/[Host]下的context配置文件中，不需要指定 path，即使指定了，也不会起作用； 也从原文档中可以看出，最好 context配置文件的名字跟 web应用程序的名字保持一致；

**Comment by Gukie** [comment]
refer: https://blog.csdn.net/xiazdong/article/details/7215052
